@startuml

title Class Diagram \n

class LoginViewController {
TFPassword : PasswordField
TFLogin : TextField
currentUser : User
LoginViewController() : construct
Action_btnSigIn() : void
enterToProgram() : void
}

class ProductListController {
table : TableView
idColumn : TableColumn
nameColumn : TableColumn
weightColumn : TableColumn
ListGroup : TreeView
removeButton : Button
explainButton : Button
TypeOfStorageItem : ArrayList
groupItems : ArrayList
isProducts : boolean
itemForReturn : TypeOfStorageItem
ProductListController() : construct
init() : void
createContextMenu() : void
initForSupply() : void
configureUI() : void
configureWeightColumn() : void
toFirst() : void
toLast() : void
toExplain() : void
getItemForReturn() : TypeOfStorageItem
addProduct() : void
removeProduct() : void
expandAllItems() : void
updateListView() : void
updateTable() : void
cancelEditName() : void
commitEditName() : void
cancelEditGroup() : void
commitEditGroup() : void
cancelEditWeight() : void
commitEditWeight() : void
}

class UsersViewController {
userTable : TableView
idColumn : TableColumn
nameColumn : TableColumn
positionColumn : TableColumn
loginColumn : TableColumn
passwordColumn : TableColumn
activeColumn : TableColumn
CheckBoxFilter : CheckBox
ComboBoxFilter : ComboBox
searchTF : TextField
usersBefore : ArrayList
positions : ArrayList
data : ObservableList
UsersViewController() : construct
init() : void
setCellValueFactory() : void
configColumns() : void
configActiveColumn() : void
configPasswordColumn() : void
configLoginColumn() : void
configNameColumn() : void
configPositionColumn() : void
showInvalidLoginErrorDialog() : void
showShortPasswordErrorDialog() : void
showShortLoginErrorDialog() : void
isDuplicateLogin() : boolean
toFirst() : void
toLast() : void
addUser() : void
toSearch() : void
showNotification() : void
toFilter() : void
}

class ZoneViewController {
idClmn : TableColumn
nameClmn : TableColumn
forProductClmn : TableColumn
numberOfCells : TableColumn
maxWeightClmn : TableColumn
table : TableView
deleteBtn : Button
contextMenu : ContextMenu
zones : ArrayList
items : ObservableList
tabPane : TabPane
ZoneViewController() : construct
init() : void
configureUI() : void
updateItems() : void
configureTable() : void
configureClmn() : void
addZone() : void
deleteZones() : void
toFirst() : void
toLast() : void
toCell() : void
}

class MainViewController {
LabelNameUser : Label
tabPane : TabPane
UserBtn : Button
PositionBtn : Button
ZonesBtn : Button
ContractorsBtn : Button
ProductListBtn : Button
MaterialListBtn : Button
catalogsVbox : VBox
myCompanyBtn : Button
productOnStorageBtn : Button
materialOnStorageBtn : Button
recordsVbox : VBox
supplyProductBtn : Button
supplyMaterialBtn : Button
dispProductBtn : Button
dispMaterialBtn : Button
moveProductBtn : Button
moveMaterialBtn : Button
bookBtn : Button
recordMenu : Button
catalogMenu : Button
currentUser : User
userList : ArrayList
supplierList : ArrayList
customerList : ArrayList
positionList : ArrayList
groupItemsList : ArrayList
typeOfStorageItemList : ArrayList
zones : ArrayList
receiptSupplies : ArrayList
receiptDispatches : ArrayList
receiptMovements : ArrayList
MainViewController() : construct
init() : void
settingAccess() : void
loadGroupList() : void
loadReceiptsMovements() : void
loadReceiptsDispatches() : void
loadReceiptsSupplies() : void
loadZones() : void
loadStorageItemList() : void
loadUsers() : void
loadCustomersAndSuppliers() : void
loadPositions() : void
toUsersView() : void
toPositionView() : void
toContractorView() : void
toMaterialList() : void
toProductList() : void
toZoneView() : void
toStockReplenishmentProduct() : void
toStockReplenishmentMaterial() : void
toStockDispatchProduct() : void
toProductOnWareHouse() : void
toMovementProduct() : void
toMovementMaterial() : void
toBooksController() : void
toMaterialOnWareHouse() : void
toStockDispatchMaterial() : void
catalogMenuClick() : void
recordMenuClick() : void
}

class createTypeStorageItemController {
nameField : TextField
weightField : TextField
btn : Button
typeOfStorageItems : ArrayList
selectedGroup : GroupItems
isProduct : boolean
createTypeStorageItemController() : construct
init() : void
btnClick() : void
}

class ReceiptDispatch {
customer : Customer
ReceiptDispatch() : construct
getCustomer() : Customer
setCustomer() : void
}

class BooksController {
table : TableView
IDColumn : TableColumn
dateColumn : TableColumn
userColumn : TableColumn
RSupply : RadioButton
RRepl : RadioButton
RMove : RadioButton
inCheckBox : CheckBox
inDateP : DatePicker
byCheckBox : CheckBox
byDateP : DatePicker
contactorCheckBox : CheckBox
contractComboBox : ComboBox
userCheckBox : CheckBox
userComboBox : ComboBox
typeOfItemCheckBox : CheckBox
typeOfItemComboBox : ComboBox
receiptSupplies : ArrayList
receiptDispatches : ArrayList
receiptMovements : ArrayList
suppliers : ArrayList
customers : ArrayList
users : ArrayList
toggleGroup : ToggleGroup
tabPane : TabPane
BooksController() : construct
init() : void
configureUI() : void
updatePersonComboBox() : void
configureTypeRadio() : void
configureTable() : void
sortOnTypeBook() : void
sortOnTypeItem() : void
sortOnDate() : void
sortOnPerson() : void
refreshTable() : void
more() : void
showReceiptSupply() : void
showReceiptDispatch() : void
showReceiptMovement() : void
}

class createUserController {
nameTextField : TextField
positionComboBox : ComboBox
loginTextField : TextField
passwordTextField : TextField
saveButton : Button
labelNameWindow : Label
root : GridPane
users : ArrayList
usersViewController : UsersViewController
createUserController() : construct
init() : void
areAllTextFieldsFilled() : boolean
addNewUser() : void
}

class movementController {
rootPane : GridPane
idTextField : TextField
datePicker : DatePicker
performerComboBox : ComboBox
invoiceNumberTextField : TextField
table : TableView
ItemColumn : TableColumn
amountOnCellColumn : TableColumn
amountColumn : TableColumn
weightItemColumn : TableColumn
fromColumn : TableColumn
sumWeightColumn : TableColumn
whereColumn : TableColumn
availableWeightColumn : TableColumn
availableAmountColumn : TableColumn
addButton : Button
removeButton : Button
finishButton : Button
receipts : ArrayList
items : ArrayList
zones : ArrayList
users : ArrayList
author : User
isProduct : boolean
cellObservableList : ObservableList
currentReceipt : ReceiptMovement
movementController() : construct
init() : void
initForRead() : void
updateTable() : void
configureUI() : void
calculateAvailableAmount() : Integer
updateFields() : void
configureTable() : void
showProductTypeList() : void
calculateAvailableWeight() : Double
calculateAmountOnCell() : Integer
updateCells() : void
updateUser() : void
isFieldsAreFilled() : boolean
isTableAreFilled() : boolean
isColumnAmountValuesNonNegative() : boolean
disableUI() : void
moveItems() : void
finish() : void
removeItem() : void
addItem() : void
commitEditAmount() : void
commitEditItem() : void
commitWhereEdit() : void
}

enum Permission {
EditingUsersAndPositions : construct
EditingWarehouseInformation : construct
ProductEditing : construct
ProductLogistic : construct
EditingContactor : construct
ViewBook : construct
Permission() : construct
values() : construct
valueOf() : construct
}

class stockDispatchController {
rootPane : GridPane
idTextField : TextField
invoiceNumberTextField : TextField
datePicker : DatePicker
addButton : Button
removeButton : Button
finishButton : Button
performerComboBox : ComboBox
customersComboBox : ComboBox
table : TableView
ItemColumn : TableColumn
cellColumn : TableColumn
amountOnCellColumn : TableColumn
amountColumn : TableColumn
availableAmountColumn : TableColumn
warehouseZones : ArrayList
typeOfStorageItems : ArrayList
receipts : ArrayList
customers : ArrayList
users : ArrayList
currentReceipt : ReceiptDispatch
typeOfStorageItemObservableList : ObservableList
userObservableList : ObservableList
customerObservableList : ObservableList
author : User
isProduct : boolean
stockDispatchController() : construct
init() : void
initForRead() : void
updateTable() : void
configureUI() : void
configureFields() : void
updateFields() : void
updateCells() : ObservableList
updateItems() : void
updateCustomers() : void
updateUser() : void
configureTable() : void
calculateAmountOnCell() : Integer
cancelEditItem() : void
cancelEditCell() : void
cancelEditAmount() : void
commitEditItem() : void
commitEditCell() : void
commitEditAmount() : void
addItem() : void
removeItem() : void
isFieldsAreFilled() : boolean
isTableAreFilled() : boolean
disableUI() : void
removeItemsFromCell() : void
finish() : void
showProductTypeList() : void
calculateAvailableAmount() : Integer
isColumnAmountValuesNonNegative() : boolean
}

class Cell {
ID : Long
currentWeight : double
name : String
stored : ArrayList
isActive : boolean
maxWeight : double
zone : WarehouseZone
Cell() : construct
addProductsAll() : boolean
addProduct() : boolean
removeItem() : void
setName() : void
getID() : long
getCurrentWeight() : double
getName() : String
isActive() : boolean
setActive() : void
getZone() : WarehouseZone
getMaxWeight() : double
getStored() : ArrayList
toString() : String
}

class cellViewController {
ComboBoxForFilter : ComboBox
checkBoxForFilter : CheckBox
table : TableView
idClmn : TableColumn
nameClmn : TableColumn
zoneClmn : TableColumn
weightClmn : TableColumn
maxWeightClmn : TableColumn
zones : ArrayList
cells : ArrayList
items : ObservableList
cellViewController() : construct
init() : void
refresh() : void
doFilter() : void
toFirst() : void
toLast() : void
}

class Position {
ID : long
name : String
permissions : ArrayList
isActive : boolean
Position() : construct
addPermission() : void
hasPermissions() : boolean
removePermissions() : void
getName() : String
setName() : void
getPermissions() : ArrayList
setPermissions() : void
getID() : long
toString() : String
clone() : Position
}

class StorageItem {
ID : long
type : TypeOfStorageItem
locationOnStorage : Cell
supplier : Supplier
customer : Customer
StorageItem() : construct
getID() : long
setID() : void
getType() : TypeOfStorageItem
setType() : void
getLocationOnStorage() : Cell
setLocationOnStorage() : void
getSupplier() : Supplier
setSupplier() : void
getCustomer() : Customer
setCustomer() : void
}

class GroupItems {
ID : long
name : String
parent : GroupItems
isProduct : boolean
GroupItems() : construct
getID() : long
setID() : void
getName() : String
setName() : void
getParent() : GroupItems
setParent() : void
isProduct() : boolean
setProduct() : void
toString() : String
}

class stockReplenishmentController {
idTextField : TextField
datePicker : DatePicker
performerComboBox : ComboBox
suppliersComboBox : ComboBox
invoiceNumberTextField : TextField
table : TableView
ItemColumn : TableColumn
quantityColumn : TableColumn
cellColumn : TableColumn
rootPane : GridPane
ItemWeightColumn : TableColumn
availableWeightClmn : TableColumn
sumWeightItem : TableColumn
addButton : Button
removeButton : Button
finishButton : Button
receipts : ArrayList
typeOfStorageItems : ArrayList
zones : ArrayList
suppliers : ArrayList
users : ArrayList
author : User
isProduct : boolean
currentReceipt : ReceiptSupply
cellObservableList : ObservableList
supplierObservableList : ObservableList
userObservableList : ObservableList
groups : ArrayList
stockReplenishmentController() : construct
init() : void
initForRead() : void
configureUI() : void
updateFields() : void
configureTable() : void
calculateAvailableWeight() : Double
updateCells() : void
updateUser() : void
updateSuppliers() : void
updateTable() : void
isColumnValuesNonNegative() : boolean
isFieldsAreFilled() : boolean
isTableAreFilled() : boolean
disableUI() : void
addItemsIntoCell() : boolean
finish() : void
showProductTypeList() : void
addItem() : void
removeItem() : void
cancelEditCell() : void
cancelEditAmount() : void
cancelEditItem() : void
commitEditItem() : void
commitEditAmount() : void
commitEditCell() : void
}

class Receipt {
ID : long
date : LocalDate
performer : User
invoiceNumberField : String
lists : ArrayList
isProduct : boolean
Receipt() : construct
getID() : long
getDate() : LocalDate
getPerformer() : User
getInvoiceNumberField() : String
getLists() : ArrayList
setLists() : void
isProduct() : boolean
setProduct() : void
}

class Contractor {
ID : long
name : String
address : String
information : String
passport : String
phone : String
bankRequisites : String
IIN : String
KPP : String
isActive : boolean
Contractor() : construct
getID() : long
getName() : String
setName() : void
getAddress() : String
setAddress() : void
getInformation() : String
setInformation() : void
getPassport() : String
setPassport() : void
getPhone() : String
setPhone() : void
getBankRequisites() : String
setBankRequisites() : void
getIIN() : String
setIIN() : void
getKPP() : String
setKPP() : void
isActive() : boolean
setActive() : void
toString() : String
clone() : Contractor
}

class User {
ID : Long
name : String
position : Position
login : String
password : String
isActive : boolean
User() : construct
setName() : void
getName() : String
getID() : Long
getPosition() : Position
setPosition() : void
getLogin() : String
setLogin() : void
getPassword() : String
setPassword() : void
isActive() : boolean
setActive() : void
toString() : String
}

class HelloApplication {
HelloApplication() : construct
start() : void
main() : void
}

class ReceiptSupply {
supplier : Supplier
ReceiptSupply() : construct
getSupplier() : Supplier
setSupplier() : void
}

class createWarehouseZoneController {
btn : Button
zoneNameField : TextField
lengthField : TextField
widthField : TextField
CBoxZoneFor : ComboBox
maxWeightField : TextField
zones : ArrayList
createWarehouseZoneController() : construct
init() : void
showAlert() : void
btnClick() : void
}

class Customer {
Customer() : construct
}

class Supplier {
Supplier() : construct
}

class CreateGroupController {
groupNameTextField : TextField
groups : ArrayList
parent : GroupItems
isProduct : boolean
CreateGroupController() : construct
init() : void
addButtonClicked() : void
}

class WarehouseZone {
ID : Long
zoneName : String
cells : Cell[][]
isActive : boolean
isProductZone : boolean
maxWeight : Double
WarehouseZone() : construct
getZoneName() : String
setZoneName() : void
getCells() : Cell[][]
setCells() : void
getID() : Long
isActive() : boolean
setActive() : void
isProductZone() : boolean
getMaxWeight() : Double
setProductZone() : void
toString() : String
}

class ContractorController {
table : TableView
columnName : TableColumn
columnIsSupplier : TableColumn
columnAddress : TableColumn
columnInformation : TableColumn
columnPassport : TableColumn
columnPhone : TableColumn
columnBankRequisites : TableColumn
columnIIN : TableColumn
columnKPP : TableColumn
btnAdd : Button
btnRemove : Button
TFName : TextField
CBisSupplier : CheckBox
TFaddress : TextField
TAInfo : TextArea
TFpassport : TextField
TFphone : TextField
TFbankRequisites : TextField
TFinn : TextField
TFkpp : TextField
CheckBoxSelection : CheckBox
comboBoxContactorType : ComboBox
boxForFields : VBox
data : ObservableList
customersBefore : ArrayList
suppliersBefore : ArrayList
ContractorController() : construct
init() : void
configureUI() : void
filteredCustomers() : void
filteredSuppliers() : void
configureClmn() : void
configureFields() : void
configureTable() : void
disableUIElements() : void
displaySelectedContractor() : void
addContractor() : void
removeContractor() : void
setTypeContractor() : void
updateTable() : void
acceptChanges() : void
cancelChanges() : void
toFirst() : void
toLast() : void
TFNameAction() : void
TFaddressAction() : void
TFpassportAction() : void
TFphoneAction() : void
TFbankRequisitesAction() : void
TFinnAction() : void
TFkppAction() : void
}

class ProductOnStorageController {
table : TableView
idColumn : TableColumn
nameColumn : TableColumn
groupColumn : TableColumn
supplierColumn : TableColumn
zoneColumn : TableColumn
cellColumn : TableColumn
amountOnWarehouseColumn : TableColumn
amountOnZoneColumn : TableColumn
amountOnCellColumn : TableColumn
labelStorage : Label
groupFilterCheckBox : CheckBox
groupFilterComboBox : ComboBox
zoneFilterCheckBox : CheckBox
zoneFilterComboBox : ComboBox
searchTextField : TextField
groupItemsObservableList : ObservableList
zoneObservableList : ObservableList
storageItemObservableList : ObservableList
zones : ArrayList
itemForReturn : StorageItem
isProduct : boolean
ProductOnStorageController() : construct
init() : void
toExplain() : void
getItemForReturn() : StorageItem
updateTable() : void
updateAllStorageItems() : void
updateZoneComboBox() : void
updateGroupComboBox() : void
configureUI() : void
configureTable() : void
calculateAmountOnWarehouseColumn() : Long
calculateAmountOnZoneColumn() : Long
calculateAmountOnCellColumn() : Long
toFirst() : void
toLast() : void
movementProduct() : void
filter() : void
}

class ReceiptMovement {
list : ArrayList
ReceiptMovement() : construct
getListMovement() : ArrayList
setListMovement() : void
}

class PositionViewController {
positionListView : ListView
positionNameField : TextField
CBEditUserAndRole : CheckBox
CBWarehouseEdit : CheckBox
CBEditProduct : CheckBox
CBViewBooks : CheckBox
CBEditLogistics : CheckBox
CBEditCounterpart : CheckBox
btnRemovePosition : Button
positions : ArrayList
PositionViewController() : construct
init() : void
configureUI() : void
configureListView() : void
disableUIElements() : void
enableUIElements() : void
displayPermissionsForPosition() : void
setEditUserAndRolePermissions() : void
setWarehouseEditPermissions() : void
removePosition() : void
addPosition() : void
showInvalidNameErrorDialog() : void
saveNewNameForPosition() : void
TFAction() : void
setEditLogisticsPermissions() : void
setEditCounterparty() : void
setEditProductType() : void
setViewBook() : void
}

class TypeOfStorageItem {
ID : long
name : String
groupItems : GroupItems
weight : double
isProduct : boolean
isActive : boolean
TypeOfStorageItem() : construct
getName() : String
setName() : void
getID() : long
getGroup() : GroupItems
setGroup() : void
getWeight() : double
setWeight() : void
isProduct() : boolean
setProduct() : void
isActive() : boolean
setActive() : void
toString() : String
}


LoginViewController --> User
LoginViewController --> MainViewController
LoginViewController --> Position
LoginViewController --> Permission
ProductListController --> createTypeStorageItemController
ProductListController --> CreateGroupController
ProductListController --> TypeOfStorageItem
ProductListController --> GroupItems
UsersViewController --> User
UsersViewController --> Position
UsersViewController --> createUserController
ZoneViewController --> createWarehouseZoneController
ZoneViewController --> WarehouseZone
MainViewController --> ReceiptMovement
MainViewController --> User
MainViewController --> Position
MainViewController --> Customer
MainViewController --> WarehouseZone
MainViewController --> TypeOfStorageItem
MainViewController --> GroupItems
MainViewController --> ReceiptSupply
MainViewController --> Permission
MainViewController --> Supplier
MainViewController --> ReceiptDispatch
createTypeStorageItemController --> TypeOfStorageItem
createTypeStorageItemController --> GroupItems
ReceiptDispatch --|> Receipt
ReceiptDispatch --> User
ReceiptDispatch --> Customer
BooksController --> ReceiptMovement
BooksController --> Receipt
BooksController --> User
BooksController --> Customer
BooksController --> ReceiptSupply
BooksController --> Contractor
BooksController --> Supplier
BooksController --> ReceiptDispatch
createUserController --> UsersViewController
createUserController --> User
createUserController --> Position
movementController --> ReceiptMovement
movementController --> User
movementController --> ProductOnStorageController
movementController --> Cell
movementController --> StorageItem
movementController --> WarehouseZone
movementController --> TypeOfStorageItem
stockDispatchController --> Customer
stockDispatchController --> ReceiptSupply
stockDispatchController --> ProductOnStorageController
stockDispatchController --> Cell
stockDispatchController --> StorageItem
stockDispatchController --> Receipt
stockDispatchController --> WarehouseZone
stockDispatchController --> User
stockDispatchController --> TypeOfStorageItem
stockDispatchController --> ReceiptDispatch
Cell --> WarehouseZone
Cell --> StorageItem
cellViewController --> WarehouseZone
cellViewController --> Cell
Position ..|> Cloneable
Position --> Permission
StorageItem --> Customer
StorageItem --> TypeOfStorageItem
StorageItem --> Supplier
StorageItem --> Cell
stockReplenishmentController --> User
stockReplenishmentController --> ReceiptSupply
stockReplenishmentController --> ProductListController
stockReplenishmentController --> Supplier
stockReplenishmentController --> Cell
stockReplenishmentController --> StorageItem
stockReplenishmentController --> Receipt
stockReplenishmentController --> WarehouseZone
stockReplenishmentController --> TypeOfStorageItem
stockReplenishmentController --> GroupItems
Receipt --> User
Receipt --> Cell
Receipt --> StorageItem
Contractor ..|> Cloneable
User --> Position
HelloApplication --|> Application
ReceiptSupply --|> Receipt
ReceiptSupply --> User
ReceiptSupply --> Supplier
createWarehouseZoneController --> WarehouseZone
Customer --|> Contractor
Supplier --|> Contractor
CreateGroupController --> GroupItems
WarehouseZone --> Cell
ContractorController --> Customer
ContractorController --> Contractor
ContractorController --> Supplier
ProductOnStorageController --> WarehouseZone
ProductOnStorageController --> GroupItems
ProductOnStorageController --> Supplier
ProductOnStorageController --> Cell
ProductOnStorageController --> StorageItem
ReceiptMovement --|> Receipt
ReceiptMovement --> User
ReceiptMovement --> Receipt
ReceiptMovement --> Cell
ReceiptMovement --> StorageItem
PositionViewController --> Position
PositionViewController --> Permission
TypeOfStorageItem --> GroupItems

@enduml
